name: Download using dotnet-file
author: David G. Moore, Jr., <david@dgmjr.io>
description: Downloads a file (or folder) using the dotnet-file tool

branding:
  icon: download-cloud
  color: blue

inputs:
  repo:
    description: The repository from which to download the file (in the format owner/repo-name)
    required: true
  filename:
    description: The file/(or folder)name/path within the repo to get
    required: false
    default: .
  destination-path:
    description: The destination path of the file (defaults to '.')
    required: false
    default: .
  hostname:
    description: The git host (if other than GitHub)
    required: false
    default: github.com
  token:
    description: The GitHub token to use for authentication
    required: false
    default: ''

runs:
  using: composite
  steps:
    - id: Ensure-dotnet-file-is-installed
      uses: dgmjr-actions/restore-dotnet-file@main
    - id: Authenticate-with-gh-if-necessary
      if: ${{ inputs.token }} != ''
      run: |
        git config --global credential.helper cache;
        git config --global credential.credentialStore cache;
        echo ${{ inputs.token }} | gh auth login --with-token && gh auth setup-git
      shell: bash
    - id: Download-the-File
      run: dotnet file add "https://${{ inputs.hostname }}/${{ inputs.repo }}/${{ inputs.filename }}"
      shell: bash
    - id: Clean-up-netconfig
      run: rm -rf .netconfig
      shell: bash
